### ISSUE TITLE
vim keybindings: `j` and `k` for navigation.

### ISSUE THREAD

**Issue by lassepe** [MichaelHatherly/InteractiveErrors.jl#4]
Thank you for this awesome package! This is a real boost for a REPL workflow!

I was wondering whether it would be possible to add support for `j` and `k` to navigate up and down in the terminal menu in a `vim`-like-fashion. I didn't dive into the details of your code but I saw that you are using `REPL.TerminalMenus`. Thus, I'm not sure whether here is the right place to file the issue or whether it should be filed upstream.

**Comment by MichaelHatherly** [comment]
Thanks, glad you're liking it.

https://github.com/JuliaLang/julia/pull/37940 is what you want. This already works out of the box in 1.7, but is very unlikely to be a backporting candidate. There's probably nothing that can be done about that unfortunately.
